# -*- coding: utf-8 -*-
"""Assignment3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JXBHsuPKFmSQ-w_0W76o-gqRuAv1UqX-
"""

#Import the libraries#
import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sympy import *

#To label the points # 
X = [0,0,8]
Y = [6,0,0]

A = [0,6]
B = [0,0]
C = [8,0]

AB_X = [0,0]
AB_Y = [6,0]
AC_X = [0,8]
AC_Y = [6,0]
BC_X = [0,8]
BC_Y = [0,0]
 

figure(figsize=(6,4.5))
plt.scatter(X,Y,color='black')
plt.annotate("A[0,6]",(0,6))
plt.annotate("B[0,0]",(0,0))
plt.annotate("C[8,0]",(8,0))
plt.plot(AB_X,AB_Y,label='AB')
plt.plot(AC_X,AC_Y,label='AC')
plt.plot(BC_X,BC_Y,label='BC')
plt.xlabel('X - axis')
plt.ylabel('Y - axis')
 
D = [72/25,96/25]
BD_X = [0,72/25]
BD_Y = [0,96/25]
plt.scatter(D[0],D[1],color='black')
plt.annotate("D",(72/25,96/25))
plt.plot(BD_X,BD_Y,label='Altitude BD')


plt.legend()
plt.grid()
plt.show()