# -*- coding: utf-8 -*-
"""Assignment3_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16CSw5XtiUgJhWhoXBgx_o1M7lSRssl_K
"""

#Import the libraries#
import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sympy import *

A = [0,6]
B = [0,0]
C = [8,0]

y = np.arange(-5,8,0.00001)

def circ_gen(C,r):
	len = 1000
	theta = np.linspace(0,2*np.pi,len)
	x_circ = np.zeros((2,len))
	x_circ[0,:] = r*np.cos(theta)
	x_circ[1,:] = r*np.sin(theta)
	x_circ = (x_circ.T + C).T
	return x_circ

centre = [4,0]
r = 4
x_circ= circ_gen(centre,r)

x1 = (0*y)
x2 = (-12*y/5)+(72/5)

figure(figsize=(7,5))
plt.plot(x_circ[0,:],x_circ[1,:])
plt.scatter(A[0],A[1],color='black')
plt.scatter(centre[0],centre[1],color='black')
plt.plot(x1,y,label='Tangent 1')
plt.plot(x2,y,label='Tangent 2')
plt.annotate("A[0,6]",(0,6))
plt.annotate("centre",(4,0))

plt.legend()
plt.grid()
plt.show()