# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YG-jNR9z5OUMXy2LPTAL4V88Fztk_ztZ
"""

import matplotlib.pyplot as plt
  
data = [n**2 for n in range(10)]
  
# separating the stem parts
stems = [0, 1, 2, 3, 4, 5,6,7,8,9]
  
plt.ylabel('x[n^2]')   # for label at y-axis
  
plt.xlabel('x[n]')   # for label at x-axis
  
plt.xlim(0, 10)   # limit of the values at x axis
  
plt.stem(stems, data)   # required plot
plt.grid()