# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KrqfuqDTLzff9LTNpRwwyQ8lnqChYQsb
"""

#Import the libraries#
import numpy as np 
import matplotlib.pyplot as plt

#To label the points # 
X = [2,4]
Y = [1,5]
#To get the line # 
X1 =[2,4,0]
Y1 = [1,5,-3]
 
plt.scatter(X,Y,label = 'Points',color='skyblue')
plt.plot(X1,Y1,color = 'orange')
plt.axhline(y=-1,linestyle = ':',color = 'green')
plt.annotate("A:[1,-1]", (1, -1)) 
plt.annotate("B",(2,1))
plt.annotate("C",(4,5))
x=[1]
y=[-1]
plt.scatter(x,y,marker = 'h',color='black')

plt.xlabel('X - axis')
plt.ylabel('Y - axis')
 
plt.legend()
plt.grid()
plt.show()