# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sc33eLYqineTMyAbHi7o7uG-fZsPZk4j
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy import pi
from scipy.fft import fft,fftshift

samp_rate = 1400
time = np.linspace(-1,1,2*samp_rate)
output = (6*(10**4)*((np.sinc(700*time))**2))+((10**6)*((np.sinc(500*time))**(3)))
freq = np.linspace(-300,300,2800)
freq_data = fft(output)
four = np.abs(freq_data)
plt.plot(freq,fftshift(four))
plt.xlabel("Frequency")
plt.ylabel("Amplitude")
plt.grid()
plt.show()