# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9pWOejKqvISqwFtW_93tfiMbu8Div5I
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy import pi
from scipy.fft import fft,fftshift

samp_rate = 1400
time = np.linspace(-1,1,2*samp_rate)
output = (6*(10**4)*((np.sinc(700*time))**2))+((10**6)*((np.sinc(500*time))**(3)))
# plot of the given signal
plt.plot(time,output)
plt.xlim(-0.015,0.015)
plt.grid()
plt.show()
freq = np.linspace(-700,700,2800)
freq_data = fft(output)
four = np.abs(freq_data)
plt.plot(freq,fftshift(four))
plt.xlabel("Frequency")
plt.ylabel("Amplitude")
plt.grid()
plt.show()