# -*- coding: utf-8 -*-
"""Gate1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cf7PDovrwquahoPD7mcgGIANKN7vLYxb
"""

# importing libraries
import numpy as np
import matplotlib.pyplot as plt
from math import *

time = np.arange(0,50,0.1)

# The function of the singnal #
Amplitude = 1 + (2*np.cos(pi*time)) + (3*np.sin(2*pi*time/3))+ (4*np.cos((pi*time/2)+(pi/4)))
# individual time periods #
tp_1 = 2
tp_2 = 3
tp_3 = 4

# Plot the graph #
plt.plot(time,Amplitude)
plt.xlabel('Time')
plt.ylabel('Amplitude')
plt.grid()

# Function to calculate the lcm #
def lcm(a,b,c):
    if a>b and a>c:
      greatest = a
    if b>c and b>a:
      greatest = b
    if c>a and c>b:
      greatest = c
    while(True):
      if((greatest % a == 0) and (greatest % b == 0) and (greatest % c == 0)):
        lcm = greatest 
        break
      greatest += 1

    return lcm
    
# To estimate the fundamental time period of the function #
ftp=lcm(tp_1,tp_2,tp_3)
print("Fundamental Time Period:",ftp,"sec")

# to plot the intervals #
plt.axvline(0,0,1,color = 'r')
plt.axvline(ftp,0,1,color='r')
plt.axvline(2*ftp,0,1,color='r')
plt.axvline(3*ftp,0,1,color='r')
plt.axvline(4*ftp,0,1,color='r')
plt.show()