# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDtydzEVXZHPinEaIREzIz5sc8Fy9nUJ
"""

import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from sympy import *
 
 
x = np.arange(-5,5,0.0001)
xt = np.arange(0,np.sqrt(3),0.0001)
xt1 = np.arange(np.sqrt(3),2,0.0001)
y1 = x/np.sqrt(3)
 
circle = plt.Circle((0,0),radius = 2 ,edgecolor='green',lw=1.5, fc='none')
plt.gca().add_patch(circle)
 
yt = xt/np.sqrt(3)
plt.fill_between(xt,0,yt,color='pink',alpha=1)
 
yt1 = np.sqrt(4-(xt1**2))
plt.fill_between(xt1,0,yt1,color='pink',alpha=1)
 
plt.plot(x,y1)
plt.axhline(0,0,1,color='r')
plt.grid()
plt.show()