# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9_wzI58jQ0o9YGzroTqqvozOmigEQuC
"""

import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from sympy import *
 
 
x = np.arange(-5,5,0.0001)
xt = np.arange(0,np.sqrt(3),0.0001)
xt1 = np.arange(np.sqrt(3),2,0.0001)
y1 = x/np.sqrt(3)
 
circle = plt.Circle((0,0),radius = 2 ,edgecolor='green',lw=1.5, fc='none')
plt.gca().add_patch(circle)
 
yt = xt/np.sqrt(3)
plt.fill_between(xt,0,yt,color='pink',alpha=1)
 
yt1 = np.sqrt(4-(xt1**2))
plt.fill_between(xt1,0,yt1,color='pink',alpha=1)

A=[np.sqrt(3),1]
plt.scatter(A[0],A[1],marker = '*',c='black')
plt.annotate('A',(np.sqrt(3),1))
B = [2,0]
plt.scatter(B[0],B[1],marker = '*',c='black')
plt.annotate('B',(2,0))
O = [0,0]
plt.scatter(O[0],O[1],marker = '*')
plt.annotate('O',(0,0))

plt.plot(x,y1)
plt.axhline(0,0,1,color='r')
plt.grid()
plt.show()