# -*- coding: utf-8 -*-
"""As2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2NZrYxuIje-68VvRovQn0GjL-ka_q-_
"""

import numpy as np
import math

At = np.array([[-2,3],[1,2]])
A = At.T
B = np.array([[-1,0],[1,2]])

sum = A+2*B
final_ans = sum.T
print(final_ans)