# -*- coding: utf-8 -*-
"""Assignment4_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBiD5lUiVQZ8aIDRHS_FdtPgWSJV0iUD
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import math 

plt3d = plt.figure().gca(projection='3d')


lam = np.arange(-10,10,0.1)
n = len(lam)
x_a = np.ones(n)*2+ lam*2
y_a = np.ones(n)*1+lam*5
z_a = np.ones(n)*(-3)+lam*(-3)
vec_a = np.array([2,5,-3])

x_b = np.ones(n)*(-2)+ lam*(-1)
y_b = np.ones(n)*4+lam*8
z_b = np.ones(n)*(5)+lam*(4)
vec_b = np.array([-1,8,4])

plt3d.plot(x_a,y_a,z_a)
plt3d.plot(x_b,y_b,z_b)

dot = vec_a @ vec_b 
angle = math.acos(dot / (np.linalg.norm(vec_a)*np.linalg.norm(vec_b)))

print("The angle between the lines  :",angle*180/math.pi,"degrees")