# -*- coding: utf-8 -*-
"""Assignment4_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFEE3TMS_zGXlA-MOeKchDmykryPVoFN
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import math 

plt3d = plt.figure().gca(projection='3d')


lam = np.arange(-10,10,0.1)
n = len(lam)
x_c =  lam*2
y_c =  lam*2
z_c =  lam*1
vec_c = np.array([2,2,1])

x_d = np.ones(n)*(-5)+ lam*(4)
y_d = np.ones(n)*(-2)+lam*(1)
z_d = np.ones(n)*(-3)+lam*(8)
vec_d = np.array([4,1,8])

plt3d.plot(x_c,y_c,z_c)
plt3d.plot(x_d,y_d,z_d)

dot = vec_c @ vec_d 
angle = math.acos(dot / (np.linalg.norm(vec_c)*np.linalg.norm(vec_d)))

print("The angle between the lines  :",angle*180/math.pi,"degrees")